### PR TITLE
Add history navigation buttons

### PR DESCRIPTION
**Pull request by xuchunyang**
The new added code is all from help-mode.el, and here is what it looks like:
screen shot 2016-02-10 at 23 17 44

### CODE REVIEW

**Comment by kuanyui** [comment]
Thank you!

**Comment by kuanyui** [comment]
And I didn't find a wrong rendering until seeing your screenshot... Let me see...

**Comment by kuanyui** [comment]
I don't sure what the fuck has happened, maybe `help-mode` (parent mode of `tldr-mode`) do some magic and it disable all faces of upper-cased strings in `tldr-mode`. I've suspected `help-highlight-arg` is the murderer, but it seems to do nothing in `tldr-mode`.

So, currently I `downcase` all upper-cased arguments. e.g. `{{COMMAND}}` , `{{FILES}}`

screenshot

**Comment by xuchunyang** [comment]
Hmm, It's very very odd, but I don't think help-mode is the cause, maybe the 4th argument `FIXEDCASE` of `replace-regexp-in-string` is (defaults to nil):

> ```
>  If FIXEDCASE is non-‘nil’, then ‘replace-match’ uses the
>  replacement text without case conversion; otherwise, it converts
>  the replacement text depending upon the capitalization of the text
>  to be replaced.  If the original text is all upper case, this
>  converts the replacement text to upper case.  If all words of the
>  original text are capitalized, this capitalizes all the words of
>  the replacement text.  If all the words are one-letter and they are
>  all upper case, they are treated as capitalized words rather than
>  all-upper-case words.
> ```

I guess text properties will be removed during case conversion, if so, set this argument to `t` should solve the issue.

**Comment by kuanyui** [comment]
Oh!!! Thank you! Merged!

**Pull request merged**
